name: Guns.lol Checker

on:
  workflow_dispatch:

jobs:
  checker:
    runs-on: ubuntu-latest

    steps:
      - name: Télécharger le projet
        uses: actions/checkout@v4

      - name: Installer Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Installer Google Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Installer les dépendances
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lancer le checker
        env:
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
        run: |
          python gunslol.py
